### ISSUE TITLE
Buttons do not respect dark/light switch

### ISSUE THREAD

**Issue by GeorgEchterling** [argyleink/open-props#342]
Buttons currently only support the user agent's preferred color scheme. They should also support the recently added [theme toggling](https://github.com/argyleink/open-props/issues/286).

**Comment by argyleink** [comment]
confirmed. ty for logging, will get on it!

**Comment by GeorgEchterling** [comment]
I looked into it some more and it looks like only [two lines in buttons.css](https://github.com/argyleink/open-props/blob/ed5a83da2f497a180b296b1eed4ca3259db82e5f/src/extra/buttons.css#L7) need to be changed.

- `--_text: initial` should be `--_text: var(--text-2)` to match the current non-switch settings. Otherwise, `initial` will refer to the `html` element's `color`, which may not match the locally selected color scheme.
- I don't know what `--_accent: initial` should be changed to. Afaict, it isn't being set anywhere.

**Comment by argyleink** [comment]
i fixed it in my local demo by reordering my imports:

HAS BUG:
```css
@import 'open-props/style';
@import 'open-props/normalize';
@import 'open-props/switch/light';
@import 'open-props/switch/dark';
@import 'open-props/buttons';
```

FIXED:
```css
@import 'open-props/style';
@import 'open-props/normalize';
@import 'open-props/buttons';
@import 'open-props/switch/light';
@import 'open-props/switch/dark';
```

This way the overrides from the switch style win based on cascade. gonna close this assuming it fixes your issue too. lemme know!

**Comment by GeorgEchterling** [comment]
This doesn't quite fix my issue. Looks like my issue is more specific than what I initially described:
- I have a global `data-theme` on my `html` element, which a user can change using a theme toggle.
- I have a local `data-theme="dark"` on my navigation, which should override the global theme for just that element. This works for everything I've tried except for the buttons' text color. (Although I haven't tried much, so there may be other parts that don't work with this setup.)

I don't know if the theme switch is intended to be used in this way. Maybe it was only intended for the root element?

**Comment by argyleink** [comment]
yeah, def intended for root propagating all the way throughout. BUT!

you could just reach in and write a button color to fix this? (maybe you've already done that)
you shouldnt need to battle Open Props styles, they're wrapped in `:where()`, so hopefully it's easy to patch for your use case? 🙂
